---
all:
  children:
    uninitialized_octopi:
      hosts:
        octopi.local:
      vars:
        ansible_ssh_pass: raspberry
        ansible_sudo_pass: raspberry
    cr10s_octopi:
      hosts:
        cr10s-octopi.local:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: pi
